import type {
  AudioOptions,
  CarUpgradeState,
  DriverStanding,
  MarinaDecoration,
  PressureCallDefinition,
  PlayerProfile,
  RivalProfile,
  SponsorContractDefinition,
  TeamSetupDefinition,
  TrackVariant,
  UpgradeDefinition,
  Vector2,
} from "./types";

const marinaLoop: Vector2[] = [
  { x: 960, y: 1140 },
  { x: 1380, y: 1100 },
  { x: 1710, y: 920 },
  { x: 1875, y: 650 },
  { x: 1795, y: 360 },
  { x: 1460, y: 220 },
  { x: 1030, y: 190 },
  { x: 645, y: 270 },
  { x: 390, y: 455 },
  { x: 325, y: 755 },
  { x: 430, y: 1010 },
  { x: 690, y: 1145 },
];

const breakerLoop: Vector2[] = [
  { x: 420, y: 1020 },
  { x: 760, y: 1180 },
  { x: 1230, y: 1210 },
  { x: 1680, y: 1120 },
  { x: 1910, y: 900 },
  { x: 1940, y: 590 },
  { x: 1810, y: 320 },
  { x: 1510, y: 180 },
  { x: 1080, y: 150 },
  { x: 680, y: 220 },
  { x: 420, y: 420 },
  { x: 310, y: 720 },
];

const skylineLoop: Vector2[] = [
  { x: 360, y: 1120 },
  { x: 770, y: 1230 },
  { x: 1360, y: 1200 },
  { x: 1770, y: 1020 },
  { x: 1910, y: 760 },
  { x: 1840, y: 460 },
  { x: 1660, y: 230 },
  { x: 1290, y: 130 },
  { x: 900, y: 145 },
  { x: 580, y: 250 },
  { x: 390, y: 450 },
  { x: 300, y: 760 },
];

const marinaDecorations: MarinaDecoration[] = [
  { kind: "pier", position: { x: 200, y: 420 }, width: 260, height: 90, tint: "#73573d" },
  { kind: "pier", position: { x: 210, y: 700 }, width: 240, height: 90, tint: "#6c5238" },
  { kind: "pier", position: { x: 220, y: 980 }, width: 250, height: 84, tint: "#705339" },
  { kind: "yacht", position: { x: 120, y: 390 }, width: 88, height: 26, tint: "#f8f4ed" },
  { kind: "yacht", position: { x: 90, y: 700 }, width: 72, height: 24, tint: "#f8f4ed" },
  { kind: "yacht", position: { x: 105, y: 990 }, width: 76, height: 26, tint: "#ffffff" },
  { kind: "building", position: { x: 1520, y: 520 }, width: 220, height: 138, tint: "#223141" },
  { kind: "building", position: { x: 1475, y: 815 }, width: 245, height: 150, tint: "#203648" },
  { kind: "building", position: { x: 1120, y: 860 }, width: 200, height: 132, tint: "#1f3241" },
  { kind: "building", position: { x: 1035, y: 470 }, width: 180, height: 96, tint: "#26384a" },
  { kind: "grandstand", position: { x: 980, y: 1290 }, width: 360, height: 72, tint: "#4c5968" },
  { kind: "grandstand", position: { x: 630, y: 1160 }, width: 200, height: 68, tint: "#45515e" },
  { kind: "tower", position: { x: 1680, y: 280 }, width: 82, height: 180, tint: "#3a4758" },
  { kind: "crane", position: { x: 1400, y: 1180 }, width: 180, height: 110, tint: "#e4b54a" },
  { kind: "lights", position: { x: 1210, y: 1240 }, width: 130, height: 48, tint: "#fee09a" },
  { kind: "palm", position: { x: 540, y: 1180 }, width: 48, height: 68, tint: "#1aa56e" },
  { kind: "palm", position: { x: 1460, y: 1230 }, width: 48, height: 68, tint: "#28aa75" },
  { kind: "palm", position: { x: 1740, y: 1010 }, width: 48, height: 68, tint: "#24a16b" },
  { kind: "palm", position: { x: 1770, y: 470 }, width: 48, height: 68, tint: "#1ba26d" },
  { kind: "palm", position: { x: 620, y: 170 }, width: 48, height: 68, tint: "#2db37d" },
];

const breakerDecorations: MarinaDecoration[] = [
  { kind: "pier", position: { x: 170, y: 560 }, width: 340, height: 86, tint: "#705235" },
  { kind: "pier", position: { x: 180, y: 840 }, width: 330, height: 86, tint: "#674a32" },
  { kind: "building", position: { x: 1560, y: 420 }, width: 260, height: 140, tint: "#203244" },
  { kind: "building", position: { x: 1260, y: 980 }, width: 220, height: 138, tint: "#1d3140" },
  { kind: "building", position: { x: 960, y: 480 }, width: 240, height: 112, tint: "#2a3948" },
  { kind: "tower", position: { x: 1480, y: 170 }, width: 88, height: 190, tint: "#344758" },
  { kind: "tower", position: { x: 1040, y: 150 }, width: 76, height: 160, tint: "#3d4f61" },
  { kind: "crane", position: { x: 1830, y: 1040 }, width: 210, height: 120, tint: "#e5b249" },
  { kind: "crane", position: { x: 1430, y: 1180 }, width: 180, height: 102, tint: "#ebb852" },
  { kind: "grandstand", position: { x: 760, y: 1320 }, width: 280, height: 70, tint: "#495868" },
  { kind: "grandstand", position: { x: 1630, y: 1180 }, width: 260, height: 66, tint: "#4d5a69" },
  { kind: "lights", position: { x: 1260, y: 1270 }, width: 160, height: 52, tint: "#ffdf96" },
  { kind: "lights", position: { x: 1860, y: 660 }, width: 132, height: 46, tint: "#ffd987" },
  { kind: "yacht", position: { x: 90, y: 520 }, width: 96, height: 28, tint: "#eef7fb" },
  { kind: "yacht", position: { x: 105, y: 860 }, width: 88, height: 26, tint: "#ffffff" },
  { kind: "palm", position: { x: 580, y: 150 }, width: 46, height: 64, tint: "#20a46f" },
  { kind: "palm", position: { x: 1910, y: 320 }, width: 46, height: 64, tint: "#2cb37c" },
  { kind: "palm", position: { x: 1770, y: 1180 }, width: 46, height: 64, tint: "#2eae79" },
];

const skylineDecorations: MarinaDecoration[] = [
  { kind: "building", position: { x: 1450, y: 320 }, width: 290, height: 180, tint: "#243547" },
  { kind: "building", position: { x: 1210, y: 360 }, width: 250, height: 160, tint: "#1b2d3d" },
  { kind: "building", position: { x: 980, y: 980 }, width: 340, height: 148, tint: "#22384a" },
  { kind: "building", position: { x: 620, y: 980 }, width: 220, height: 130, tint: "#2a4051" },
  { kind: "tower", position: { x: 1680, y: 170 }, width: 96, height: 240, tint: "#415465" },
  { kind: "tower", position: { x: 1340, y: 120 }, width: 88, height: 220, tint: "#3b4d5f" },
  { kind: "tower", position: { x: 930, y: 120 }, width: 84, height: 210, tint: "#344659" },
  { kind: "grandstand", position: { x: 1640, y: 1180 }, width: 320, height: 68, tint: "#4b5967" },
  { kind: "grandstand", position: { x: 590, y: 1260 }, width: 280, height: 64, tint: "#55626f" },
  { kind: "lights", position: { x: 1110, y: 1280 }, width: 180, height: 54, tint: "#ffe39e" },
  { kind: "lights", position: { x: 1870, y: 890 }, width: 140, height: 46, tint: "#ffdd91" },
  { kind: "crane", position: { x: 280, y: 1080 }, width: 140, height: 110, tint: "#f0bb58" },
  { kind: "pier", position: { x: 170, y: 1120 }, width: 250, height: 84, tint: "#5c4534" },
  { kind: "pier", position: { x: 170, y: 840 }, width: 250, height: 84, tint: "#664c38" },
  { kind: "yacht", position: { x: 100, y: 1100 }, width: 90, height: 24, tint: "#f5fbff" },
  { kind: "yacht", position: { x: 120, y: 820 }, width: 84, height: 24, tint: "#ffffff" },
];

export const DEFAULT_AUDIO_OPTIONS: AudioOptions = {
  muted: false,
  master: 0.8,
  music: 0.62,
  sfx: 0.84,
};

export const DEFAULT_UPGRADES: CarUpgradeState = {
  engine: 0,
  tyres: 0,
  brakes: 0,
  armor: 0,
  nitro: 0,
};

export const POINTS_TABLE = [12, 10, 8, 6, 5, 4, 3];

export const UPGRADE_DEFINITIONS: UpgradeDefinition[] = [
  {
    key: "engine",
    label: "Vector Stage Engine",
    shortLabel: "Engine",
    summary: "Raise top speed and pull harder out of the bigger Phase 2 circuits.",
    effect: "+ speed, + acceleration",
    costs: [550, 780, 980, 1220, 1510],
  },
  {
    key: "tyres",
    label: "Harbour Compound Tyres",
    shortLabel: "Tyres",
    summary: "Recover faster when weather, dust, or painted runoff starts turning the track against you.",
    effect: "+ grip, + off-track recovery",
    costs: [470, 670, 880, 1090, 1340],
  },
  {
    key: "brakes",
    label: "Dockside Brake Pack",
    shortLabel: "Brakes",
    summary: "Carry confidence into longer circuits and late-brake showdowns without turning every stop into a slide.",
    effect: "+ braking, + turn-in stability",
    costs: [430, 600, 790, 970, 1190],
  },
  {
    key: "armor",
    label: "Kevlar Body Shell",
    shortLabel: "Armor",
    summary: "Make a seven-round career survivable when the field gets wider and the damage bills start snowballing.",
    effect: "- collision damage",
    costs: [520, 730, 930, 1170, 1430],
  },
  {
    key: "nitro",
    label: "Slipstream Nitro Kit",
    shortLabel: "Nitro",
    summary: "Stretch your passing windows across endurance laps and high-stakes showdown exits.",
    effect: "+ boost reserve, + boost force",
    costs: [410, 590, 770, 960, 1190],
  },
];

export const TEAM_SETUPS: TeamSetupDefinition[] = [
  {
    key: "balanced",
    label: "Balanced trim",
    summary: "Default crew plan with no obvious weakness and no hidden trick.",
    effect: "Neutral pace, neutral wear, neutral risk",
    maxSpeedDelta: 0,
    accelerationDelta: 0,
    brakeForceDelta: 0,
    turnRateDelta: 0,
    gripDelta: 0,
    damageTakenMultiplier: 1,
    wearFactor: 1,
    boostCapacityDelta: 0,
    boostForceDelta: 0,
    boostRechargeDelta: 0,
  },
  {
    key: "attack",
    label: "Attack trim",
    summary: "Sharper launch and stronger top-end for sprint rounds, at the cost of a car that gets messy faster.",
    effect: "+ pace and nitro, - stability, + wear",
    maxSpeedDelta: 10,
    accelerationDelta: 18,
    brakeForceDelta: -10,
    turnRateDelta: -0.05,
    gripDelta: -0.18,
    damageTakenMultiplier: 1.04,
    wearFactor: 1.08,
    boostCapacityDelta: 12,
    boostForceDelta: 10,
    boostRechargeDelta: 0.8,
  },
  {
    key: "endurance",
    label: "Endurance trim",
    summary: "A calmer setup that protects the shell across long-distance rounds and ugly weather.",
    effect: "- peak speed, + wear control, + repair resilience",
    maxSpeedDelta: -6,
    accelerationDelta: -4,
    brakeForceDelta: 12,
    turnRateDelta: 0.04,
    gripDelta: 0.12,
    damageTakenMultiplier: 0.94,
    wearFactor: 0.82,
    boostCapacityDelta: 2,
    boostForceDelta: -4,
    boostRechargeDelta: 1.5,
  },
  {
    key: "stability",
    label: "Stability trim",
    summary: "Brake and grip bias for wall-heavy circuits where a tidy car beats a dramatic one.",
    effect: "+ braking and grip, - headline speed",
    maxSpeedDelta: -4,
    accelerationDelta: -2,
    brakeForceDelta: 22,
    turnRateDelta: 0.12,
    gripDelta: 0.24,
    damageTakenMultiplier: 0.88,
    wearFactor: 0.9,
    boostCapacityDelta: -4,
    boostForceDelta: -6,
    boostRechargeDelta: 0.4,
  },
];

export const SPONSOR_CONTRACTS: SponsorContractDefinition[] = [
  {
    id: "vector-works",
    name: "Vector Works Parts",
    tag: "Launch partner",
    summary: "The in-house backer keeps the season moving with a light parts discount while you prove the career can stand on its own.",
    objectiveLabel: "Finish P4 or better in any round.",
    bonusLabel: "Pays 120 cr and trims upgrade invoices by 5%.",
    bonusCredits: 120,
    unlockRound: 0,
    upgradeDiscount: 0.05,
    objective: {
      requiredFinish: 4,
    },
  },
  {
    id: "harbor-union",
    name: "Harbor Union Mutual",
    tag: "Clean-run insurer",
    summary: "A cautious marina insurer that rewards tidy finishes and makes repair decisions less punishing.",
    objectiveLabel: "Finish P5 or better with at least 72% condition left.",
    bonusLabel: "Pays 180 cr and cuts repair quotes by 18%.",
    bonusCredits: 180,
    unlockRound: 2,
    repairDiscount: 0.18,
    objective: {
      requiredFinish: 5,
      minCondition: 72,
    },
  },
  {
    id: "tidefire-energy",
    name: "Tidefire Energy",
    tag: "Headline pace",
    summary: "A bright, impatient sponsor that wants sprint podiums and is happy to subsidize raw pace.",
    objectiveLabel: "Podium in a circuit or showdown event.",
    bonusLabel: "Pays 260 cr and trims upgrade invoices by 8%.",
    bonusCredits: 260,
    unlockRound: 3,
    upgradeDiscount: 0.08,
    objective: {
      requiredFinish: 3,
      eventTypes: ["circuit", "showdown"],
    },
  },
  {
    id: "deep-current",
    name: "Deep Current Logistics",
    tag: "Long-haul freight",
    summary: "Endurance-minded freight money that values finishing strength and a car that still has something left at the flag.",
    objectiveLabel: "Finish P4 or better in an endurance round with at least 60% condition left.",
    bonusLabel: "Pays 300 cr and cuts repair quotes by 12%.",
    bonusCredits: 300,
    unlockRound: 3,
    repairDiscount: 0.12,
    objective: {
      requiredFinish: 4,
      minCondition: 60,
      eventTypes: ["endurance"],
    },
  },
  {
    id: "skyline-broadcast",
    name: "Skyline Broadcast",
    tag: "Metro finals media",
    summary: "Late-season media money that only cares about the glamorous skyline rounds and expects a podium story to film.",
    objectiveLabel: "Podium at Vector Mile.",
    bonusLabel: "Pays 380 cr for a Metro Finals podium run.",
    bonusCredits: 380,
    unlockRound: 5,
    objective: {
      requiredFinish: 3,
      locations: ["Vector Mile"],
    },
  },
];

export const PRESSURE_CALLS: PressureCallDefinition[] = [
  {
    key: "night-shift",
    label: "Night Shift Overclock",
    tag: "Spend for pace",
    summary: "Keep the crew in after-hours and squeeze one more headline shove out of the current parts bill.",
    effect: "Spend 240 cr for a temporary engine and nitro push next event.",
    cost: 240,
    unlockRound: 4,
    tempUpgradeBoosts: {
      engine: 1,
      nitro: 1,
    },
  },
  {
    key: "spotter-bribe",
    label: "Spotter Bribe",
    tag: "Work the rivalry",
    summary: "Pay for dockside intel and make the current championship rival second-guess the clean racing line.",
    effect: "Spend 180 cr to take the edge off the lead rival in the next event.",
    cost: 180,
    unlockRound: 4,
    rivalSkillDelta: -0.08,
    rivalAggressionDelta: 0.08,
  },
  {
    key: "bonus-clause",
    label: "Bonus Clause Gamble",
    tag: "Back yourself",
    summary: "Sell the sponsor desk on a late-season statement: beat the target rival cleanly and the garage gets paid.",
    effect: "No upfront cost. Finish in the top three and ahead of the target rival for +220 cr.",
    cost: 0,
    unlockRound: 4,
    bonusCredits: 220,
    requiredFinish: 3,
  },
];

export const RIVALS: RivalProfile[] = [
  {
    id: "cass-vale",
    name: "Cass Vale",
    callsign: "Dock Queen",
    color: "#ff6f61",
    accent: "#ffd2b4",
    carNumber: "07",
    sponsor: "Vale Marine Tech",
    style: "Aggressive exit speed and a habit of pinching you against the barriers.",
    description: "The local favorite. Cass treats the marina like inherited property and hates rookies who survive contact.",
    skill: 0.91,
    aggression: 0.9,
    laneBias: -0.16,
  },
  {
    id: "ivo-mercer",
    name: "Ivo Mercer",
    callsign: "Silk Brake",
    color: "#59d7ff",
    accent: "#d8f8ff",
    carNumber: "22",
    sponsor: "Mercer Precision",
    style: "Clean braking points, low mistake rate, ruthless undercut pace.",
    description: "An old circuit scholar who wins by never being slightly wrong. Ivo is the benchmark for consistency.",
    skill: 0.95,
    aggression: 0.52,
    laneBias: 0.12,
  },
  {
    id: "mara-kade",
    name: "Mara Kade",
    callsign: "Wake Thief",
    color: "#4ee18f",
    accent: "#d9ffe8",
    carNumber: "31",
    sponsor: "Wakegrid Freight",
    style: "Lives on draft pulls and late boosts through the middle sector.",
    description: "Mara is less famous than Cass or Ivo, but she knows how to steal a finish while everyone else fights.",
    skill: 0.82,
    aggression: 0.64,
    laneBias: 0.18,
  },
  {
    id: "tomas-rook",
    name: "Tomas Rook",
    callsign: "Yard Dog",
    color: "#f1bb4a",
    accent: "#fff1c7",
    carNumber: "44",
    sponsor: "Dockline Security",
    style: "Heavy hands, shallow corner patience, and permanent shoulder pressure.",
    description: "Rook never found a contact he didn't like. He is slower on pure pace but terrific at turning your race into a repair invoice.",
    skill: 0.76,
    aggression: 0.94,
    laneBias: -0.08,
  },
  {
    id: "nia-vesk",
    name: "Nia Vesk",
    callsign: "Cold Current",
    color: "#9fe45f",
    accent: "#ebffd6",
    carNumber: "58",
    sponsor: "Northwake Logistics",
    style: "Patient setup, ruthless late-apex exits, and almost no panic inputs.",
    description: "Nia arrives once the season gets bigger. She is less theatrical than Cass and more dangerous because of it.",
    skill: 0.88,
    aggression: 0.48,
    laneBias: 0.06,
  },
  {
    id: "sable-hart",
    name: "Sable Hart",
    callsign: "Tower Ghost",
    color: "#d9dee7",
    accent: "#ffffff",
    carNumber: "63",
    sponsor: "Hart Aerodynamics",
    style: "High-commitment urban lines, sharp confidence under lights, and clinical sprint pace.",
    description: "Sable comes alive on the skyline events, where confidence between walls matters more than brute force.",
    skill: 0.86,
    aggression: 0.67,
    laneBias: -0.02,
  },
];

export const TRACK_VARIANTS: TrackVariant[] = [
  {
    id: "harbour-dawn",
    name: "Harbour Dawn Dash",
    subtitle: "Rookie Cup // Round 1",
    series: "Rookie Cup",
    location: "Southport Marina",
    weatherLabel: "Clear channel air",
    eventType: "circuit",
    eventTypeLabel: "Circuit",
    overview: "Clear skies, fresh paint, and a crowd that still thinks you might embarrass yourself.",
    briefing:
      "Southport is awake before the ferries. The opener is still about proving you belong, but now it is also the start of a longer seven-round season.",
    objective: "Finish clean, protect the car, and bank enough money to make the garage matter before the season widens.",
    ambience: "sunrise",
    laps: 3,
    width: 196,
    purse: [900, 700, 520, 360, 260, 180, 120],
    centerline: marinaLoop,
    hazards: [
      { id: "dawn-oil", label: "Fuel sheen", type: "oil", position: { x: 1710, y: 1010 }, radius: 54, intensity: 0.82 },
    ],
    hazardNotes: "One light oil patch on the cargo exit. Learn it early and you gain confidence everywhere else.",
    decorations: marinaDecorations,
    tutorialFocus: [
      "Hold throttle through the long bottom straight, then breathe the brake into the right-hand cargo bend.",
      "Damage now carries across a much longer calendar. The first round is about leaving with options, not just a trophy chase.",
      "Cass Vale in the coral car will attack the exit kerbs. Leave her room until you know the grip.",
    ],
    heatTag: "Southport still teaches rhythm before it starts demanding resilience.",
    gripModifier: 1,
    wearRate: 0.78,
  },
  {
    id: "cargo-slip",
    name: "Cargo Slip Sprint",
    subtitle: "Rookie Cup // Round 2",
    series: "Rookie Cup",
    location: "Southport Marina",
    weatherLabel: "Dusty crosswind",
    eventType: "circuit",
    eventTypeLabel: "Sprint circuit",
    overview: "More grip has burned away and the service road is now lined with containers and impatient stewards.",
    briefing:
      "Security tightens the cargo lane, the wind cuts across the north quay, and Tomas Rook is expected to turn the first sector ugly.",
    objective: "Use the garage well, survive the heavy traffic line, and keep points pressure on the front row.",
    ambience: "golden",
    laps: 4,
    width: 190,
    purse: [1100, 860, 650, 480, 340, 220, 160],
    centerline: marinaLoop,
    hazards: [
      { id: "cargo-oil-a", label: "Forklift spill", type: "oil", position: { x: 1810, y: 520 }, radius: 62, intensity: 1 },
      { id: "cargo-barrier", label: "Container pinch", type: "barrier", position: { x: 645, y: 260 }, radius: 58, intensity: 0.9 },
    ],
    hazardNotes: "Two danger zones: the forklift spill before the towers and a container squeeze at the north quay.",
    decorations: marinaDecorations,
    tutorialFocus: [
      "Brake upgrades help here. The second round punishes lazy corner entry more than raw courage.",
      "Repair before shopping if your condition is low. A faster car is useless when the season still has five rounds left.",
      "Tomas Rook in the yellow car will barge through the top quay. Expect contact.",
    ],
    heatTag: "The marina stops being picturesque and starts billing you for mistakes.",
    gripModifier: 0.95,
    wearRate: 0.96,
  },
  {
    id: "floodlight-run",
    name: "Floodlight Run",
    subtitle: "Rookie Cup // Round 3",
    series: "Rookie Cup",
    location: "Southport Marina",
    weatherLabel: "Night floodlights",
    eventType: "circuit",
    eventTypeLabel: "Night circuit",
    overview: "Night falls, the grandstands finally fill, and the opener decides whether you are a name or a note.",
    briefing:
      "Everything important in the first cup ends here. The lights are live, the crowd knows the rivalry, and Ivo Mercer expects to win by being cleaner than you over the final laps.",
    objective: "Leave Southport with momentum, hold nerve under lights, and set up the bigger coastal rounds to come.",
    ambience: "dusk",
    laps: 4,
    width: 188,
    purse: [1400, 1080, 820, 620, 420, 260, 180],
    centerline: marinaLoop,
    hazards: [
      { id: "night-oil", label: "Lighting rig leak", type: "oil", position: { x: 455, y: 980 }, radius: 56, intensity: 0.9 },
      { id: "night-barrier", label: "Security gate", type: "barrier", position: { x: 1460, y: 1175 }, radius: 64, intensity: 1 },
      { id: "night-boost", label: "Slipstream strip", type: "boost", position: { x: 1090, y: 205 }, radius: 48, intensity: 0.7 },
    ],
    hazardNotes: "The final marina round adds a risky boost strip on the north side and harsher barriers under the floodlights.",
    decorations: marinaDecorations,
    tutorialFocus: [
      "Use nitro sparingly: the north quay boost strip can give you a free launch if you keep the line tidy.",
      "Ivo Mercer in the cyan car rarely misses an apex. Beat him with exits and smart upgrades, not panic dives.",
      "Winning Southport matters, but the season does not stop here anymore.",
    ],
    heatTag: "Southport becomes a premium night race instead of a polite local exhibition.",
    gripModifier: 0.98,
    wearRate: 1.04,
  },
  {
    id: "breaker-point",
    name: "Breaker Point Endurance",
    subtitle: "Breaker Series // Round 4",
    series: "Breaker Series",
    location: "Breaker Point",
    weatherLabel: "Sea-mist rain",
    eventType: "endurance",
    eventTypeLabel: "Endurance",
    overview: "The season widens into a wet coastal breakwater where the walls stay close and the race lasts long enough to punish optimism.",
    briefing:
      "Breaker Point is the first real Phase 2 circuit. The layout is longer, the rain is greasy, and the whole field now expects your Southport run to mean something.",
    objective: "Survive the first endurance round, keep the shell together, and prove the garage choices scale beyond the opener.",
    ambience: "golden",
    laps: 5,
    width: 184,
    purse: [1700, 1320, 1020, 760, 520, 340, 240],
    centerline: breakerLoop,
    hazards: [
      { id: "breaker-oil", label: "Slip road spray", type: "oil", position: { x: 1820, y: 930 }, radius: 60, intensity: 1 },
      { id: "breaker-boost", label: "Breakwater chute", type: "boost", position: { x: 710, y: 220 }, radius: 46, intensity: 0.62 },
      { id: "breaker-barrier", label: "Sea wall", type: "barrier", position: { x: 1450, y: 190 }, radius: 60, intensity: 1 },
    ],
    hazardNotes: "Breaker Point adds wet grip loss, one narrow sea wall, and a risky boost chute near the upper coast road.",
    decorations: breakerDecorations,
    tutorialFocus: [
      "Endurance rounds quietly burn condition away. The car does not need dramatic crashes to start hurting.",
      "Tyres and armor carry more value here than a single raw-speed purchase.",
      "Nia Vesk joins the front of the field. She punishes sloppy exits more than reckless contact.",
    ],
    heatTag: "The season becomes a real career once Breaker Point starts taxing the car every lap.",
    gripModifier: 0.88,
    wearRate: 1.28,
  },
  {
    id: "channel-showdown",
    name: "Channel Knife Showdown",
    subtitle: "Breaker Series // Round 5",
    series: "Breaker Series",
    location: "Breaker Point",
    weatherLabel: "Crosswind evening",
    eventType: "showdown",
    eventTypeLabel: "Showdown",
    overview: "A stripped-back three-rival duel with no traffic to hide behind and no excuse for getting lost in the pack.",
    briefing:
      "The season pauses for a purse-heavy showcase. Only the sharpest three rivals line up with you, and every clean pass matters more because there is nowhere to disappear.",
    objective: "Beat the headline names in a compact field and turn raw pace into reputation.",
    ambience: "dusk",
    laps: 4,
    width: 180,
    purse: [1850, 1280, 880, 520],
    centerline: breakerLoop,
    hazards: [
      { id: "showdown-barrier", label: "Knife-edge wall", type: "barrier", position: { x: 330, y: 710 }, radius: 58, intensity: 0.96 },
      { id: "showdown-oil", label: "Spray line", type: "oil", position: { x: 1880, y: 610 }, radius: 50, intensity: 0.8 },
    ],
    hazardNotes: "Short field, bigger purses, and less room to blame the pack for bad decisions.",
    decorations: breakerDecorations,
    tutorialFocus: [
      "A showdown round rewards clean pace. You cannot hide a weak line in a smaller field.",
      "Cass, Ivo, and Nia are the benchmark trio here. If you beat them, it means something.",
      "With fewer cars around, the garage should feel like a tuning room rather than just a repair station.",
    ],
    heatTag: "Breaker Point cuts the field down until the season feels personal.",
    gripModifier: 0.93,
    wearRate: 1.12,
    fieldIds: ["cass-vale", "ivo-mercer", "nia-vesk"],
  },
  {
    id: "skyline-classic",
    name: "Skyline Sprint Classic",
    subtitle: "Metro Finals // Round 6",
    series: "Metro Finals",
    location: "Vector Mile",
    weatherLabel: "Sunset haze",
    eventType: "circuit",
    eventTypeLabel: "Sprint circuit",
    overview: "The walls tighten, the towers wake up, and the season turns from dockside grit into premium urban speed.",
    briefing:
      "Vector Mile is the glossy circuit the sponsors want on posters. That means higher speed, tighter confidence, and Sable Hart finally arriving in her home territory.",
    objective: "Translate your dockyard craft into skyline precision without donating the bodywork to concrete.",
    ambience: "golden",
    laps: 4,
    width: 182,
    purse: [2000, 1520, 1160, 860, 620, 420, 280],
    centerline: skylineLoop,
    hazards: [
      { id: "skyline-barrier-a", label: "Service tunnel wall", type: "barrier", position: { x: 1780, y: 1030 }, radius: 58, intensity: 1 },
      { id: "skyline-boost", label: "Express lane strip", type: "boost", position: { x: 950, y: 145 }, radius: 46, intensity: 0.8 },
      { id: "skyline-oil", label: "Tower runoff", type: "oil", position: { x: 590, y: 250 }, radius: 54, intensity: 0.88 },
    ],
    hazardNotes: "Faster walls, a premium boost strip, and almost no time to recover a lazy skyline line.",
    decorations: skylineDecorations,
    tutorialFocus: [
      "Skyline events reward brake discipline and confidence between walls more than raw aggression.",
      "Sable Hart is strongest here. If she disappears early, the lap was probably yours to save rather than hers to steal.",
      "The urban rounds are where the expanded career should start feeling premium instead of merely larger.",
    ],
    heatTag: "The season stops pretending it is a local marina story and becomes a city circuit league.",
    gripModifier: 1,
    wearRate: 1.04,
  },
  {
    id: "stormbelt-run",
    name: "Stormbelt Gauntlet",
    subtitle: "Metro Finals // Round 7",
    series: "Metro Finals",
    location: "Vector Mile",
    weatherLabel: "Storm front",
    eventType: "endurance",
    eventTypeLabel: "Storm endurance",
    overview: "The finale runs under a storm wall where the skyline is half light, half threat, and the season finally asks the whole garage to matter.",
    briefing:
      "This is the full-career proof point: bad weather, long distance, stronger rivals, and enough accumulated consequence that every repair and upgrade choice should show up on track.",
    objective: "Bring the season home with a car that still responds, a wallet that still matters, and a result worth replaying for.",
    ambience: "dusk",
    laps: 5,
    width: 178,
    purse: [2400, 1780, 1340, 980, 720, 480, 320],
    centerline: skylineLoop,
    hazards: [
      { id: "storm-oil", label: "Rain sheen", type: "oil", position: { x: 360, y: 450 }, radius: 58, intensity: 1 },
      { id: "storm-barrier", label: "Flood gate", type: "barrier", position: { x: 1660, y: 230 }, radius: 62, intensity: 1 },
      { id: "storm-boost", label: "Charge lane", type: "boost", position: { x: 1330, y: 120 }, radius: 48, intensity: 0.78 },
    ],
    hazardNotes: "The season finale cuts grip, raises wear, and turns every clean skyline exit into a title-defining moment.",
    decorations: skylineDecorations,
    tutorialFocus: [
      "Storm rounds are not won by heroics alone. A half-broken car will lie to you about what it can still do.",
      "Save the biggest nitro punch for a clean exit, not a desperate entry under bad weather.",
      "If this finale makes you want another full season immediately, the Phase 2 foundation is doing its job.",
    ],
    heatTag: "The storm finale is where the whole garage loop either pays off or exposes itself.",
    gripModifier: 0.84,
    wearRate: 1.38,
  },
];

export const MENU_VARIANT_ID = TRACK_VARIANTS[0].id;

export function createInitialStandings(): DriverStanding[] {
  return [
    {
      driverId: "player",
      name: "You",
      color: "#ff8454",
      accent: "#ffe3c9",
      carNumber: "01",
      sponsor: "Vector Works",
      points: 0,
      purse: 0,
      bestFinish: 99,
      lastFinish: null,
      bestLapMs: null,
      isPlayer: true,
    },
    ...RIVALS.map((rival) => ({
      driverId: rival.id,
      name: rival.name,
      color: rival.color,
      accent: rival.accent,
      carNumber: rival.carNumber,
      sponsor: rival.sponsor,
      points: 0,
      purse: 0,
      bestFinish: 99,
      lastFinish: null,
      bestLapMs: null,
      isPlayer: false,
    })),
  ];
}

export function createInitialProfile(): PlayerProfile {
  return {
    credits: 1080,
    condition: 100,
    upgrades: { ...DEFAULT_UPGRADES },
    selectedSetup: TEAM_SETUPS[0].key,
    activeSponsorId: SPONSOR_CONTRACTS[0].id,
    status: "idle",
    currentHeatIndex: 0,
    standings: createInitialStandings(),
    history: [],
    bestTimeTrialMs: {},
    options: { ...DEFAULT_AUDIO_OPTIONS },
    tutorialSeen: false,
    activePressureCallKey: null,
    activePressureCallRound: null,
  };
}

export function getVariantById(variantId: string) {
  return TRACK_VARIANTS.find((variant) => variant.id === variantId) ?? TRACK_VARIANTS[0];
}

export function getSponsorContractById(contractId: string) {
  return SPONSOR_CONTRACTS.find((contract) => contract.id === contractId) ?? SPONSOR_CONTRACTS[0];
}

export function getPressureCallByKey(key: PlayerProfile["activePressureCallKey"]) {
  return PRESSURE_CALLS.find((call) => call.key === key) ?? null;
}

export function getTeamSetupByKey(key: PlayerProfile["selectedSetup"]) {
  return TEAM_SETUPS.find((setup) => setup.key === key) ?? TEAM_SETUPS[0];
}
